disableStartupPopups: false
notARepository: "quit"

os:
  editPreset: "vscode"

promptToReturnFromSubprocess: false # removes "press enter to return to lazygit" popup

gui:
  showBottomLine: false
  showListFooter: false
  showCommandLog: true
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - black
      - bold
